# Generated by Django 4.2.11 on 2025-01-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0003_interaction_reminder_alter_movie_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="meetings", to="webapp.user"
            ),
        ),
    ]
